### ISSUE TITLE
Show exact date on hover

### ISSUE THREAD

**Issue by prees1** [wokalski/covid-19charts.com#3]
Really great work with this @wokalski - couldn't agree more with this type of chart being critical to help people understand their own situation in context to others! 👏 

One idea I had was to show the _exact_ day for a given set of y values, on hover:

You see here:
![image](https://user-images.githubusercontent.com/6665997/76625194-1a649100-650d-11ea-8324-4580e9f2b6b6.png)

I see it is only on narrow width views too, although it is really apparent on mobile.

You can't see exactly what the day is, have to assume it is 11, be great if it always showed the day number that you are hovering on (either in the axis or in the onhover box).

Reason being, it is easier to calculate, future growth predictions, doubling time, etc. I see you have other TODOs here on that too. 👍 

Again, thanks for this, and great work! Hope this is helpful.

**Comment by wokalski** [comment]
I will try to add it this evening. Thanks. Do you have any insights when it comes to presentation of future growth predictions or doubling time? I'm also thinking about creating a growth rate graph to have a bare insight into it (instead of just looking at the slope)

**Comment by prees1** [comment]
Cool, thanks!

Yea showing future values based on the slope makes sense. 

I think what would be useful is to see, the exact _date_ (not 'day number') in the future, paired with the expected number of cases. Maybe only showing the doubling points (vs every day), with the associated values. - Just an idea really, but that would easily help see where things are heading for different countries/regions.

John Burn-Murdoch from the Financial Times actually has a similar graph - https://twitter.com/jburnmurdoch/status/1237737352879112194

Your work here is already just as good if not better than his, being fully interactive and dynamic. One thing he does include is a x% increase slope line, which is nice as a reference point

**Comment by wokalski** [comment]
@prees1 Here's how it looks:
<img width="987" alt="image" src="https://user-images.githubusercontent.com/1693190/76661057-bf698300-657a-11ea-99fe-6f31dc8dc6ad.png">

**Comment by wokalski** [comment]
I should've done it since the beginning.

<img width="1002" alt="image" src="https://user-images.githubusercontent.com/1693190/76661838-aeba0c80-657c-11ea-9cb3-baf8bef92157.png">

**Comment by wokalski** [comment]
> I think what would be useful is to see, the exact date (not 'day number') in the future, paired with the expected number of cases.

Since users can switch between `days since` and calendar view (btw do you have a suggestion how to name those? `Align to day 0` is cryptic) it should probably show either a date or number of days accordingly.

> One thing he does include is a x% increase slope line, which is nice as a reference point

Good point. I'll add it, too.

**Comment by prees1** [comment]
Sweet, thanks so much!

Oh yea great point having them align to those timelines makes complete sense. I actually hadn't even tried the 'dates' timeline, mode. I find the offset one to be the useful one, to more easily compare the rate of change.

As for the names, I can try and help with some ideas. 

'Align to day 0' 
- 'shift relative to threshold', describes what is happening to the lines themselves. maybe it is to wordy? 'relative to threshold' or 'relative'?

- 'days after threshold', describes the axis itself, maybe that could be an axis label. John does like 'number of days since 17th case', which seems useful.

for 'dates'
- maybe 'timeline' or to contrast the relative idea above, 'absolute'?

Just some ideas, hope it helps.
