### ISSUE TITLE
Add new cases chart

### ISSUE THREAD

**Issue by scooler** [wokalski/covid-19charts.com#5]
I guess this is one chart type, but a new-cases is also interesting. 
Both number, and percentage of the existing (as it's a % of the existing cases) - as seeon on Wikipedia for example :D - https://en.wikipedia.org/wiki/2020_coronavirus_pandemic_in_Italy#Timeline

And even (what I had an idea for) - new cases as a percentage, but not of every case, but of the recent new cases. Because if a country accumulated thousands of positive cases in the hospitals or homes, they don't spread the virus (or shouldn't). What's more interesting is how fast does it sprepread based on how fast did it spread recently. Because today's new cases would be based on yesterday's new cases' connections :) This would give us a good (better IMO) for how easy it is to spread divided by how cautious/socially distant people are. 
IMO we'd see quite a difference between places like Italy and Japan or China.

**Comment by wokalski** [comment]
Resolved by a2df2fd35d98b1a20cd6739c92b8737748e60b62

I think it addresses the issue. Let me know if u have any suggestions.
