### ISSUE TITLE
Use contrasting colors

### ISSUE THREAD

**Issue by narfdotpl** [wokalski/covid-19charts.com#7]
Hey,

Nice idea with charts. Potentially useful for comparing situation between countries. 👍 Sadly I can't say which country is which on the chart. Their colors all look the same to me. I'm color blind but this shouldn't be so bad. I suggest using a color palette designed for data visualization instead of picking colors [randomly](https://github.com/wokalski/covid-19charts.com/blob/4b0fac8adfc3ba2948f84ca41024f87ccca26318/src/Data.re#L24-L27). One of the popular ones is [ColorBrewer](http://bl.ocks.org/mhkeller/10504471). I think the "paired" scale would work well. I'm not sure how to install it in JS these days (or whatever `.re` is 🙃) but I've used the [version from d3js.org](https://d3js.org/colorbrewer.v1.min.js) in the past.

🌈📈

**Comment by wokalski** [comment]
im not colorblind but I can't tell the difference either lol. I'm fixing it.

**Comment by narfdotpl** [comment]
❤️

**Comment by wokalski** [comment]
Resolved in 45edc79

**Comment by narfdotpl** [comment]
<img width="1058" alt="Screenshot 2020-03-24 at 17 54 35" src="https://user-images.githubusercontent.com/113496/77454275-9954a600-6df8-11ea-9e61-3af17288192a.png">

🙌
