### ISSUE TITLE
Color country changes when removing country

### ISSUE THREAD

**Issue by IwanKaramazow** [wokalski/covid-19charts.com#9]
Start state:
<img width="203" alt="image" src="https://user-images.githubusercontent.com/10634678/77728811-94147880-6ffd-11ea-8f21-7bc634b64b15.png">

When deleting Spain, Belgium's color changes:
<img width="208" alt="image" src="https://user-images.githubusercontent.com/10634678/77728937-d3db6000-6ffd-11ea-9eb9-4282f4312abf.png">

Would it be better if the color of Belgium stayed the same?
For a minute I thought Belgium disappeared, couldn't find it on the graph anymore.

**Comment by wokalski** [comment]
Yeah, it's annoying
